### ISSUE TITLE
Tracking Issue: v0.1.0

### ISSUE THREAD

**Issue by milesgranger** [milesgranger/caroline#1]
- [x] Implement `::new(...)` for all types (#2)
- [x] Make parameters refer to other types generated from the specification (#3)
- [X] Generate `ResouceTypes` and `PropertyTypes` (#4)
- [ ] Locate and implement when `Ref` is needed, that it refers to the struct
- [ ] Dump to CloudFormation
